# fly.toml file generated for buying-frenzy-dipto on 2022-08-04T21:56:44+06:00

app = "buying-frenzy-dipto"
kill_signal = "SIGTERM"
kill_timeout = 5

[processes]
    web = "serve"

[env]
    DB_HOST = "buying-frenzy.internal"
    DB_PORT = 5432
    DB_USER = "postgres"
    DB_PASSWORD = "956cfb292fa9189332dc28d3237aa3ff63bb7c89bbec27ae"
    DB_NAME = "buying-frenzy"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

internal_port = 8080
protocol = "tcp"

[[services]]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
